### ISSUE TITLE
v1.0.3 not available in Maven central

### ISSUE THREAD

**Issue by lnhrdt** [Mercateo/test-clock#3]
Hey there! Saw the new version in the Github releases but wasn't able to pull it from Maven Central.
https://mvnrepository.com/artifact/com.mercateo/test-clock

Assuming it was supposed to be published, I thought I'd file an issue. Any chance of publishing the new version?

**Comment by StephanPraetsch** [comment]
I must confess this component hasn't been released for a while and now needs a new configuration for a release. I hope I can tackle this soon (next week). I'm sorry.

**Comment by lnhrdt** [comment]
Totally understand! Thanks for keeping the project going and I'll just keep an eye out.

**Comment by StephanPraetsch** [comment]
1.0.4 just has been released :) https://central.sonatype.com/artifact/com.mercateo/test-clock/1.0.4

**Comment by JonasGroeger** [comment]
I guess this can be closed then?

**Comment by lnhrdt** [comment]
@StephanPraetsch thanks for the latest release and getting it published in Maven Central!

@JonasGroeger sounds good.
